load("@rules_apple//apple:ios.bzl", "ios_application")
load("@rules_cc//cc:defs.bzl", "objc_library")

objc_library(
    name = "app_sources",
    srcs = [
        "AppDelegate.h",
        "AppDelegate.m",
        "main.m",
    ],
    sdk_frameworks = [
        "CoreLocation",
        "UIKit",
    ],
    deps = [
        "//plugins/gltf-layer:GltfLayer",
        "//plugins/rectangle-layer:RectangleLayer",
        "//plugins/ngon-layer:NgonLayer",
        "@maplibre//platform:ios-sdk",
    ],
)

ios_application(
    name = "PluginGallery",
    bundle_id = "org.maplibre.plugins.gallery",
    families = ["iphone"],
    infoplists = ["Info.plist"],
    minimum_os_version = "14.0",
    resources = [
        "//:positron_gltf_style",
        "//:rectangle_style",
        "//:ngon_style",
    ],
    visibility = ["//visibility:public"],
    deps = [":app_sources"],
)
