# Generated by scripts/generate.mjs; do not edit.
PLUGIN_DEPS = [
    "//plugins/gltf-layer:GltfLayer",
    "//plugins/heatmap-layer:HeatmapLayer",
    "//plugins/hillshade-layer:HillshadeLayer",
    "//plugins/ngon-layer:NgonLayer",
    "//plugins/rectangle-layer:RectangleLayer"
]
PLUGIN_RESOURCES = [
    "//plugins/gltf-layer:example_assets",
    "//plugins/ngon-layer:example_assets",
    "//plugins/rectangle-layer:example_assets"
]
