// Generated by scripts/generate.mjs; do not edit.
#import "PluginCatalog.h"
#import <GltfLayer/GltfLayer.h>
#import <HeatmapLayer/HeatmapLayer.h>
#import <HillshadeLayer/HillshadeLayer.h>
#import <NgonLayer/NgonLayer.h>
#import <RectangleLayer/RectangleLayer.h>
BOOL RegisterGalleryPlugins(NSError **error) {
    if (![MLNGltfLayerPlugin registerPluginWithError:error]) return NO;
    if (![MLNHeatmapLayerPlugin registerPluginWithError:error]) return NO;
    if (![MLNHillshadeLayerPlugin registerPluginWithError:error]) return NO;
    if (![MLNNgonLayerPlugin registerPluginWithError:error]) return NO;
    if (![MLNRectangleLayerPlugin registerPluginWithError:error]) return NO;
    return YES;
}
NSArray<NSDictionary *> *GalleryScenes(void) {
    return @[
        @{ @"key": @"model", @"title": @"Eiffel Tower GLTF", @"style": @"positron-gltf", @"camera": @[@48.8582621, @2.2944962, @650, @62, @28] },
        @{ @"key": @"ngon", @"title": @"Capital Atlas", @"style": @"ngon-style", @"camera": @[@48.8566, @2.3522, @20000, @0, @0] },
        @{ @"key": @"rectangle", @"title": @"Rectangle layer", @"style": @"rectangle-style", @"camera": @[@48.8566, @2.3522, @20000, @0, @0] },
    ];
}
