load("@rules_apple//apple:macos.bzl", "macos_command_line_application")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test", "objc_library")

filegroup(
    name = "positron_gltf_style",
    srcs = ["examples/android-app/app/src/main/assets/positron-gltf.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "rectangle_style",
    srcs = ["examples/android-app/app/src/main/assets/rectangle-style.json"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "tinygltf",
    srcs = ["vendor/tinygltf/tiny_gltf.cc"],
    hdrs = [
        "vendor/tinygltf/json.hpp",
        "vendor/tinygltf/stb_image.h",
        "vendor/tinygltf/stb_image_write.h",
        "vendor/tinygltf/tiny_gltf.h",
    ],
    includes = ["vendor/tinygltf"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "render_tests",
    srcs = ["render-tests/main.cpp"],
    copts = ["-std=c++20"],
    data = [
        "MODULE.bazel",
        "//plugins:render_test_data",
    ],
    tags = ["no-sandbox"],
    target_compatible_with = ["@platforms//os:linux"],
    deps = [
        ":render_test_registry",
        "//plugins:render_test_plugins",
        "@maplibre//render-test:render-test-srcs",
        "@maplibre//vendor:maplibre-native-base",
    ],
)

cc_library(
    name = "render_test_registry",
    hdrs = ["render-tests/plugin_registry.hpp"],
    includes = ["render-tests"],
    visibility = ["//visibility:public"],
    deps = ["@maplibre//:plugin-api"],
)

objc_library(
    name = "render_tests_metal_lib",
    srcs = ["render-tests/main.cpp"],
    copts = ["-std=c++20"],
    deps = [
        ":render_test_registry",
        "//plugins:render_test_plugins_metal",
        "@maplibre//render-test:render-test-srcs",
        "@maplibre//vendor:maplibre-native-base",
    ],
)

macos_command_line_application(
    name = "render_tests_metal",
    minimum_deployment_os_version = "14.0",
    minimum_os_version = "14.0",
    visibility = ["//visibility:public"],
    deps = [":render_tests_metal_lib"],
)
