filegroup(
    name = "liberty_shadow_style",
    srcs = ["examples/android-app/app/src/main/assets/liberty-shadow.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "positron_gltf_style",
    srcs = ["examples/android-app/app/src/main/assets/positron-gltf.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "rectangle_style",
    srcs = ["examples/android-app/app/src/main/assets/rectangle-style.json"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "tinygltf",
    srcs = ["vendor/tinygltf/tiny_gltf.cc"],
    hdrs = [
        "vendor/tinygltf/json.hpp",
        "vendor/tinygltf/stb_image.h",
        "vendor/tinygltf/stb_image_write.h",
        "vendor/tinygltf/tiny_gltf.h",
    ],
    includes = ["vendor/tinygltf"],
    visibility = ["//visibility:public"],
)
