// swift-tools-version: 5.9
// Generated by scripts/generate.mjs. Edit plugin-owned swift-targets.swift files.
import PackageDescription
import Foundation

let packageRoot = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
let nativeRevision = try! String(contentsOf: packageRoot.appendingPathComponent("native-revision.txt"), encoding: .utf8)
    .trimmingCharacters(in: .whitespacesAndNewlines)
let nativeDependency: Package.Dependency
if let path = ProcessInfo.processInfo.environment["MAPLIBRE_NATIVE_PATH"] {
    nativeDependency = .package(name: "maplibre-native", path: path)
} else {
    nativeDependency = .package(url: "https://github.com/maplibre/maplibre-native.git", revision: nativeRevision)
}

let package = Package(
    name: "MapLibreNativePlugins",
    platforms: [.iOS(.v14), .macOS(.v10_15)],
    products: [
        .library(name: "GltfLayer", targets: ["GltfLayer"]),
        .library(name: "HeatmapLayer", targets: ["HeatmapLayer"]),
        .library(name: "HillshadeLayer", targets: ["HillshadeLayer"]),
        .library(name: "NgonLayer", targets: ["NgonLayer"]),
        .library(name: "RectangleLayer", targets: ["RectangleLayer"]),
    ],
    dependencies: [nativeDependency],
    targets: [
        .target(
        name: "TinyGLTF",
        path: "plugins/gltf-layer/vendor/tinygltf",
        exclude: [
        "CMakeLists.txt", "LICENSE", "Makefile", "README.md", "appveyor.yml", "cmake", "examples",
        "examples.bat", "experimental", "loader_example.cc", "models", "premake5.lua", "test_runner.py",
        "tests", "vcsetup.bat", "wasm",
        ],
        sources: ["tiny_gltf.cc"],
        publicHeadersPath: "."
        ),
        .target(
        name: "GltfLayer",
        dependencies: [.product(name: "MapLibrePluginApi", package: "maplibre-native"), "TinyGLTF"],
        path: "plugins/gltf-layer",
        exclude: [
        "BUILD.bazel",
        "README.md",
        "plugin.json", "swift-targets.swift", "examples",
        "android",
        ],
        sources: [
        "ios/src/GltfLayer.mm",
        "shared/cpp/gltf_layer.cpp",
        ],
        publicHeadersPath: "ios/include",
        cxxSettings: [
        .headerSearchPath("shared/include"),
        .define("MLN_GLTF_PLUGIN_VERSION", to: "\"0.1.0\""),
        ],
        linkerSettings: [
        .linkedFramework("Foundation"),
        ]
        ),
        .target(
        name: "HeatmapLayer",
        dependencies: [.product(name: "MapLibrePluginApi", package: "maplibre-native")],
        path: "plugins/heatmap-layer",
        exclude: [
        "BUILD.bazel",
        "README.md",
        "plugin.json", "swift-targets.swift", "examples",
        "android",
        "render-tests",
        ],
        sources: [
        "ios/src/HeatmapLayer.mm",
        "shared/cpp/heatmap_layer.cpp",
        ],
        publicHeadersPath: "ios/include",
        cxxSettings: [
        .headerSearchPath("shared/include"),
        .define("MLN_HEATMAP_PLUGIN_VERSION", to: "\"0.1.0\""),
        ],
        linkerSettings: [
        .linkedFramework("Foundation"),
        ]
        ),
        .target(
        name: "HillshadeLayer",
        dependencies: [.product(name: "MapLibrePluginApi", package: "maplibre-native")],
        path: "plugins/hillshade-layer",
        exclude: [
        "BUILD.bazel",
        "README.md",
        "plugin.json", "swift-targets.swift", "examples",
        "android",
        "render-tests",
        ],
        sources: [
        "ios/src/HillshadeLayer.mm",
        "shared/cpp/hillshade_layer.cpp",
        ],
        publicHeadersPath: "ios/include",
        cxxSettings: [
        .headerSearchPath("shared/include"),
        .define("MLN_HILLSHADE_PLUGIN_VERSION", to: "\"0.1.0\""),
        ],
        linkerSettings: [
        .linkedFramework("Foundation"),
        ]
        ),
        .target(
        name: "NgonLayer",
        dependencies: [.product(name: "MapLibrePluginApi", package: "maplibre-native")],
        path: "plugins/ngon-layer",
        exclude: [
        "BUILD.bazel",
        "README.md",
        "plugin.json", "swift-targets.swift", "examples",
        "android",
        "render-tests", "scripts", "tests", "release.json", "build.gradle.kts",
        ],
        sources: [
        "ios/src/NgonLayer.mm",
        "shared/cpp/ngon_layer.cpp",
        ],
        publicHeadersPath: "ios/include",
        cxxSettings: [
        .headerSearchPath("shared/include"),
        .define("MLN_NGON_PLUGIN_VERSION", to: "\"0.1.0\""),
        ],
        linkerSettings: [
        .linkedFramework("Foundation"),
        ]
        ),
        .target(
        name: "RectangleLayer",
        dependencies: [.product(name: "MapLibrePluginApi", package: "maplibre-native")],
        path: "plugins/rectangle-layer",
        exclude: [
        "BUILD.bazel",
        "README.md",
        "plugin.json", "swift-targets.swift", "examples",
        "android",
        "render-tests",
        ],
        sources: [
        "ios/src/RectangleLayer.mm",
        "shared/cpp/rectangle_layer.cpp",
        ],
        publicHeadersPath: "ios/include",
        cxxSettings: [
        .headerSearchPath("shared/include"),
        .define("MLN_RECTANGLE_PLUGIN_VERSION", to: "\"0.1.0\""),
        ],
        linkerSettings: [
        .linkedFramework("Foundation"),
        ]
        ),
    ],
    cxxLanguageStandard: .cxx20
)
