// swift-tools-version: 5.9
// Generated by tools/bin/plugin generate from plugin.json; do not edit.
import PackageDescription
import Foundation

// Plugins compile against the header-only MapLibrePluginApi product of the plugin-enabled
// MapLibre iOS package. Applications link its MapLibre product, which provides
// mln_plugin_register_v1. Set MAPLIBRE_IOS_PATH to a local checkout of that package to
// test an unreleased build.
let mapLibreIOS: Package.Dependency
let mapLibreIOSPackage: String
if let path = ProcessInfo.processInfo.environment["MAPLIBRE_IOS_PATH"] {
    mapLibreIOS = .package(path: path)
    mapLibreIOSPackage = URL(fileURLWithPath: path).standardizedFileURL.lastPathComponent
} else {
    mapLibreIOS = .package(url: "https://github.com/louwers/maplibre-ios-with-plugin-api", exact: "7.0.0-pre1")
    mapLibreIOSPackage = "maplibre-ios-with-plugin-api"
}

// The target spans the repository root, so exclude everything except the plugin sources,
// their headers and the generated Objective-C wrapper (tools/, render-tests/, build/, ...).
let sources = [
    "src/square_layer.cpp",
    "apple/src/SquareLayer.mm",
]
let keptDirectories: Set<String> = ["apple", "include", "src"]
let headerExtensions: Set<String> = ["h", "hh", "hpp", "hxx", "inc", "inl", "ipp"]
let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent()

func excludedFiles(in directory: String) -> [String] {
    let files = FileManager.default.enumerator(atPath: root.appendingPathComponent(directory).path)?
        .compactMap { $0 as? String } ?? []
    return files.compactMap { file in
        let path = directory + "/" + file
        var isDirectory: ObjCBool = false
        FileManager.default.fileExists(atPath: root.appendingPathComponent(path).path, isDirectory: &isDirectory)
        if isDirectory.boolValue || sources.contains(path) || headerExtensions.contains((file as NSString).pathExtension) {
            return nil
        }
        return path
    }
}

let topLevel = (try? FileManager.default.contentsOfDirectory(atPath: root.path)) ?? []
let excluded = topLevel.filter { !keptDirectories.contains($0) && !sources.contains($0) }
    + keptDirectories.sorted().flatMap(excludedFiles(in:))

let package = Package(
    name: "SquareLayer",
    platforms: [.iOS("15.5")],
    products: [
        .library(name: "SquareLayer", targets: ["SquareLayer"]),
    ],
    dependencies: [mapLibreIOS],
    targets: [
        .target(
            name: "SquareLayer",
            dependencies: [.product(name: "MapLibrePluginApi", package: mapLibreIOSPackage)],
            path: ".",
            exclude: excluded,
            sources: sources,
            publicHeadersPath: "apple/include",
            cSettings: [
                .headerSearchPath("include"),
                .define("MLN_PLUGIN_VERSION", to: "\"0.1.0\""),
            ],
            cxxSettings: [
                .headerSearchPath("include"),
                .define("MLN_PLUGIN_VERSION", to: "\"0.1.0\""),
            ],
            linkerSettings: [
                .linkedFramework("Foundation"),
            ]
        ),
    ],
    cxxLanguageStandard: .cxx20
)
