load(":render_tests.bzl", "render_test_plugin_targets")
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "render_test_plugins",
    visibility = ["//visibility:public"],
    deps = render_test_plugin_targets("render_test_plugin"),
)

cc_library(
    name = "render_test_plugins_metal",
    visibility = ["//visibility:public"],
    deps = render_test_plugin_targets("render_test_plugin_metal"),
)

filegroup(
    name = "render_test_data",
    srcs = render_test_plugin_targets("render_test_data"),
    visibility = ["//visibility:public"],
)
