# Generated by scripts/generate.mjs; do not edit.
RENDER_TEST_PLUGIN_PACKAGES = [
    "gltf-layer",
    "heatmap-layer",
    "hillshade-layer",
    "ngon-layer",
    "rectangle-layer"
]

def render_test_plugin_targets(target):
    return ["//plugins/{}:{}".format(package, target) for package in RENDER_TEST_PLUGIN_PACKAGES]
