// Generated by tools/bin/plugin generate from plugin.json; do not edit.
#import <SquareLayer/SquareLayer.h>

#include "square_layer.h"

NSErrorDomain const MLNSquareLayerPluginErrorDomain = @"org.maplibre.plugins.square-layer";

@implementation MLNSquareLayerPlugin

+ (NSString *)version {
    return @"0.1.0";
}

+ (BOOL)registerPluginWithError:(NSError **)error {
    char message[512] = {};
    const mln_plugin_status status = mln_square_layer_register(&mln_plugin_register_v1, message, sizeof(message));
    if (status == MLN_PLUGIN_STATUS_OK || status == MLN_PLUGIN_STATUS_ALREADY_REGISTERED) {
        return YES;
    }
    if (error) {
        NSString *description = message[0] ? [NSString stringWithUTF8String:message]
                                            : @"MapLibre rejected the Square layer plugin";
        *error = [NSError errorWithDomain:MLNSquareLayerPluginErrorDomain
                                     code:status
                                 userInfo:@{NSLocalizedDescriptionKey: description ?: @""}];
    }
    return NO;
}

@end
