// Generated by tools/bin/plugin generate from plugin.json; do not edit.
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

/** Error domain of errors returned by `+[MLNSquareLayerPlugin registerPluginWithError:]`. */
FOUNDATION_EXPORT NSErrorDomain const MLNSquareLayerPluginErrorDomain;

/**
 Registers the Square layer plugin (version 0.1.0) with MapLibre.

 Call it before creating a map that loads a style using the plugin's layer types.
 Registering again succeeds.
 */
NS_SWIFT_NAME(SquareLayerPlugin)
@interface MLNSquareLayerPlugin : NSObject

/** The plugin version. */
@property (class, nonatomic, readonly) NSString *version;

/**
 Registers the plugin's layer types.

 @param error Set to the reason when registration fails.
 @return `YES` when the plugin is registered.
 */
+ (BOOL)registerPluginWithError:(NSError *_Nullable *_Nullable)error NS_SWIFT_NAME(registerPlugin());

- (instancetype)init NS_UNAVAILABLE;

@end

NS_ASSUME_NONNULL_END
